###############################################################################################
###Complete setup for Pi-hole with DNS-over-TLS, OpenVPN-AS, and Watchtower for auto-updates###
###############################################################################################

### For Pihole issue with Ubuntu/Debian distro when starting container:failed to bind host port 53/tcp: address already in use:
#Do the following steps:
# sudo vim /etc/systemd/resolved.conf
# Uncomment and change DNSStubListener=yes to no
# restart the service: sudo service systemd-resolved restart

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "4443:443/tcp"
    environment:
      - "TZ=Europe/Rome"
      - "DNS1=172.30.9.2#5054"
      - "DNS2=no"
      - "DNSMASQ_LISTENING=all"
    volumes:
      - /your/directory/pihole/etc-pihole:/etc/pihole/
      - /your/directory/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - cloudflared
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.4'
    networks:
      internal:
        ipv4_address: 172.30.9.3

  cloudflared:
    container_name: cloudflared
    restart: always
    image: visibilityspots/cloudflared
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.2'
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "5053", "cloudflare.com"]
      interval: 30s
      retries: 3
    networks:
      internal:
        ipv4_address: 172.30.9.2

  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - MKNOD
    ports:
      - 943:943
      - 443:443
      - 1194:1194/udp
    volumes:
      - /your/directory/openvpn:/openvpn
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '0.4'
    networks:
      internal:
        ipv4_address: 172.30.9.4

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 86400

networks:
  internal:
    ipam:
      config:
        - subnet: 172.30.9.0/29
