global:
    scrape_interval: 10s
    scrape_timeout: 10s

scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['hostlocalipaddress:2000']

  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'node'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['hostlocalipaddress:9100']

  - job_name: "cadvisor"
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['hostlocalipaddress:9200']


