global:
    scrape_interval: 10s
    scrape_timeout: 10s

scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['hostlocalipaddress:2000']

  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'node'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['hostlocalipaddress:9100']

  - job_name: 'traefik'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    static_configs:
            - targets: ['your.traefikdomain.com:2000']
    basic_auth:
      username: add username here
      password: add hash password here
