version: "3.7"

services:
  traefik:
    image: traefik:latest (a specific version image is recommended, instead of latest)
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    depends_on:
      - authelia      
    ports:
      - 80:80
      - 443:443    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
## The line below is not needed if you will implement Authelia##      
      - ./data/.htpasswd:/.htpasswd:ro ##File generated for user:generatedhashkey##
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`yourdomain.com`)" 
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
## The line below is not needed if you will implement Authelia## 
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:generatedhashkey"
## Add the line below ONLY if you want to implement Authelia with Traefik ##      
      - "traefik.http.routers.traefik-secure.middlewares=authelia@docker"
      
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - /your/directory/authelia:/var/lib/authelia
      - /your/directory/authelia/config:/config
      - /your/directory/authelia/config/users_database.yml:/your/directory/authelia/config/users_database.yml
    environment:
      - TZ=US/Pacific
    expose:
      - 9091
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia-secure.entrypoints=https"
      - "traefik.http.routers.authelia-secure.rule=Host(`auth.explanet.xyz`)"
      - "traefik.http.routers.authelia-secure.tls=true"
      - "traefik.http.routers.authelia-secure.tls.certresolver=http"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.explanet.xyz/"
    restart: always

  plexms:
    container_name: plex
    restart: always
    image: linuxserver/plex
      - /your/directory/path/plex:/config
      - /your/directory/path/Downloads/plex_tmp:/transcode
      - /your/directory/path/shared:/shared
## Add the line below to mount a specific folder/drive ##      
      - /your/hdd0/path:/media/hdd0
      - /your/hdd1/path:/media/hdd1
    ports:
      - "32400:32400/tcp"
      - "1900:1900/udp"
      - "3005:3005"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=http"
      - "traefik.http.routers.plex.rule=Host(`yourdomain.com`)"
      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plex.middlewares=plex-https-redirect"
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.tls.certresolver=http"
      - "traefik.http.routers.plex-secure.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=proxy"
    networks:
      proxy:

networks:
  proxy:
    external: true
    driver: bridge

